#!/usr/bin/env bash
# Link this repo into an AOSP checkout so lunch can see omadroid_x86_64.
# Does not download AOSP.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=lib.sh
source "$ROOT/scripts/lib.sh"

AOSP_ROOT="${AOSP_ROOT:-}"

usage() {
  cat <<EOF
Link Omadroid into an AOSP tree.

Usage:
  prepare-aosp.sh --aosp <aosp-root>
  AOSP_ROOT=<aosp-root> prepare-aosp.sh

Creates:
  <aosp>/vendor/modoterra/omadroid  -> this repo
  <aosp>/device/modoterra/omadroid  -> this repo's device/

Then, in that AOSP tree:
  source build/envsetup.sh
  lunch $(omadroid_lunch_combo)
  m
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --aosp)
      AOSP_ROOT="${2:-}"
      shift 2
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      omadroid_die "unknown argument: $1"
      ;;
  esac
done

[[ -n "$AOSP_ROOT" ]] || omadroid_die "pass --aosp <dir> or set AOSP_ROOT"
AOSP_ROOT="$(cd "$AOSP_ROOT" && pwd)"

[[ -f "${AOSP_ROOT}/build/envsetup.sh" ]] || omadroid_die "${AOSP_ROOT} is not an AOSP tree (missing build/envsetup.sh)"
[[ -f "${AOSP_ROOT}/device/generic/goldfish/64bitonly/product/sdk_phone64_x86_64.mk" ]] || \
  omadroid_die "${AOSP_ROOT} has no goldfish sdk_phone64_x86_64 product"

vendor_dir="${AOSP_ROOT}/vendor/modoterra/omadroid"
device_dir="${AOSP_ROOT}/device/modoterra/omadroid"

# Do not symlink the whole repo: Soong would walk sdk/, avd/, and .git.
if [[ -L "$vendor_dir" ]]; then
  rm -f "$vendor_dir"
fi
mkdir -p "$vendor_dir"
ln -sfn "${ROOT}/omadroid.mk" "${vendor_dir}/omadroid.mk"
ln -sfn "${ROOT}/device" "${vendor_dir}/device"
# Real app dirs so Soong finds Android.bp without ALLOW_BP_UNDER_SYMLINKS.
omadroid_stage_soong_app "$ROOT" "$vendor_dir" launcher
omadroid_stage_soong_app "$ROOT" "$vendor_dir" shell
if [[ -d "${ROOT}/shell/plugins" ]]; then
  ln -sfn "${ROOT}/shell/plugins" "${vendor_dir}/shell/plugins"
fi

# Soong's finder does not descend into directory symlinks unless
# ALLOW_BP_UNDER_SYMLINKS=true. Keep a real device/ directory so lunch
# always finds AndroidProducts.mk.
if [[ -L "$device_dir" ]]; then
  rm -f "$device_dir"
fi
mkdir -p "$device_dir"
cat >"${device_dir}/AndroidProducts.mk" <<EOF
# Generated by prepare-aosp.sh. Product makefiles live in the Omadroid repo.
PRODUCT_MAKEFILES := \\
    vendor/modoterra/omadroid/device/omadroid_x86_64.mk

COMMON_LUNCH_CHOICES := \\
    $(omadroid_lunch_combo)
EOF

[[ -e "${vendor_dir}/omadroid.mk" ]] || omadroid_die "vendor omadroid.mk link failed"
[[ -f "${device_dir}/AndroidProducts.mk" ]] || omadroid_die "device AndroidProducts.mk missing"

# Soong packages host test zips from Install files. When OUT_DIR is
# absolute, those paths fail as "outside directory". Skip them.
soong_dir="${AOSP_ROOT}/build/soong"
soong_patch="${ROOT}/device/patches/soong-skip-absolute-host-paths-in-test-package.patch"
if [[ -f "$soong_patch" ]]; then
  if git -C "$soong_dir" apply --check --reverse "$soong_patch" >/dev/null 2>&1; then
    printf 'omadroid: soong host-path skip already applied\n'
  elif git -C "$soong_dir" apply --check "$soong_patch" >/dev/null 2>&1; then
    git -C "$soong_dir" apply "$soong_patch"
    printf 'omadroid: applied soong host-path skip\n'
  else
    omadroid_die "soong host-path skip does not apply to ${soong_dir}"
  fi
fi

printf 'omadroid: vendor -> %s\n' "$vendor_dir"
printf 'omadroid: device -> %s\n' "$device_dir"
printf 'omadroid: lunch %s\n' "$(omadroid_lunch_combo)"
printf 'omadroid: ready. lunch %s && m\n' "$(omadroid_lunch_combo)"
